name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
        
      - name: Publish Test Results
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: ${{ github.workspace }}/ExtentReports/*.html
          
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn test
